resolver: lts-19.33
packages:
  - .
extra-deps:
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 815085bd4d50309f6089306fb4b5484b3fde6847
    subdirs:
      - .
      - liquid-base
      - liquid-prelude
      - liquid-ghc-prim
      - liquid-containers
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: a45f8fe9f6ac2533228f9149926bf884a3525945
  - rest-rewrite-0.4.0@sha256:be93d899f7dece33f2a7613eb3dabd24d139f9cb2fc09f9efedfdce4ba6eb276,3923
nix:
  packages: [cacert, git, hostname, z3]